---
#This task ensures all the required variables to run the role are defined
- name: assert required vars
  assert:
    that: "{{ item }} is defined"
    quiet: true
    fail_msg: "Variable '{{ item }}' must be defined"
  loop:
    - "script_test_name"
    - "container_test_params"
  loop_control:
    label: "Checking if variable '{{ item }}' if defined"
