---
# tasks file for docker_container_test
- name: install dependencies to run module
  include_tasks: "00_install_dependencies.yml"

- name: assert mandatory variables
  include_tasks: "01_assert_required_vars.yml"

- name: copy test files
  include_tasks: "02_copy_test_files.yml"

- name: execute tests
  include_tasks: "03_do_test.yml"
